blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog_app.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path('blog/', include('blog_app.urls', namespace='blog_app')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_app/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed


app_name = 'blog_app'


urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share,
         name='post_share'),
    path('tag/<slug:tag_slug>/', views.post_list,
         name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search')
]

blog_app/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from taggit.managers import TaggableManager


class User(AbstractUser):
    pass


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(
            PublishedManager, self).get_queryset().filter(status="published")


class Post(models.Model):
    STATUS_CHOICES = (("draft", "Draft"), ("published", "Published"))
    title = models.CharField(max_length=250)
    cover = models.ImageField(upload_to='uploads/', null=True)
    slug = models.SlugField(max_length=250, unique_for_date="publish")
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE, related_name="blog_posts"
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default="draft"
    )

    tags = TaggableManager()

    objects = models.Manager()  # The default manager.
    published = PublishedManager()  # Our custom manager.

    class Meta:
        ordering = ("-publish",)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            'blog_app:post_detail',
            args=[
                self.publish.year, self.publish.month,
                self.publish.day, self.slug
            ]
        )


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog_app/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=50)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()

blog_app/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# from django.views.generic import ListView
from django.core.mail import send_mail
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SearchForm
from taggit.models import Tag


# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/list.html'

def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)  # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html',
                  {'page': page, 'posts': posts, 'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post, slug=post, status='published', publish__year=year,
        publish__month=month, publish__day=day
    )
    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    return render(request, 'blog/post/detail.html',
                  {
                      'post': post, 'comments': comments,
                      'new_comment': new_comment,
                      'comment_form': comment_form,
                      'similar_posts': similar_posts,
                  })


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'mabasics175@gmail.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html',
                  {'post': post, 'form': form, 'sent': sent})


def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)

        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            # results = Post.published.annotate(
            #     search=search_vector,
            #     rank=SearchRank(search_vector, search_query)
            # ).filter(rank__gte=0.3).order_by('-rank')
            results = Post.published.annotate(
                similarity=TrigramSimilarity('title', query),
            ).filter(similarity__gt=0.1).order_by('-similarity')

    return render(request, 'blog/post/search.html',
                  {'form': form, 'query': query, 'results': results})

templates/blog/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load static %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <div class="blog-title-area text-center">
        <ol class="breadcrumb hidden-xs-down">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Blog</a></li>
            <li class="breadcrumb-item active">{{ post.title }}</li>
        </ol>

        <span class="color-orange"><a href="tech-category-01.html" title="">Technology</a></span>

        <h3>{{ post.title }}</h3>

        <div class="blog-meta big-meta">
            <small><a href="detail.html" title="">{{ post.publish }}</a></small>
            <small><a href="tech-author.html" title="">by {{ post.author }}</a></small>
            <small><a href="#" title=""><i class="fa fa-eye"></i> 2344</a></small>
        </div><!-- end meta -->

        <div class="post-sharing">
            <ul class="list-inline">
                <li><a href="#" class="tw-button btn btn-primary"><i class="fa fa-twitter"></i> <span class="down-mobile">Tweet on Twitter</span></a></li>
                <li><a href="{% url 'blog_app:post_share' post.id %}" class="fb-button btn btn-primary"><i class="fa fa-envelope"></i><span class="down-mobile">Share via Email</span></a></li>
            </ul>
        </div><!-- end post-sharing -->
    </div><!-- end title -->

    <div class="single-post-media">
        <img src="upload/tech_menu_08.jpg" alt="" class="img-fluid">
    </div><!-- end media -->

    <div class="blog-content">
        <div class="pp">
            {{ post.body|markdown }}
        </div><!-- end pp -->

    </div><!-- end content -->

    <div class="blog-title-area">
        <div class="tag-cloud-single">
            <span>Tags</span>
            {% for tag in post.tags.all %}
                <small><a href="{% url 'blog_app:post_list_by_tag' tag.slug %}" title="">{{ tag.name }}</a></small>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </div><!-- end meta -->

        <div class="post-sharing">
            <ul class="list-inline">
                <li><a href="#" class="tw-button btn btn-primary"><i class="fa fa-twitter"></i> <span class="down-mobile">Tweet on Twitter</span></a></li>
                <li><a href="{% url 'blog_app:post_share' post.id %}" class="fb-button btn btn-primary"><i class="fa fa-envelope"></i><span class="down-mobile">Share via Email</span></a></li>
            </ul>
        </div><!-- end post-sharing -->
    </div><!-- end title -->

    <div class="row">
        <div class="col-lg-12">
            <div class="banner-spot clearfix">
                <div class="banner-img">
                    <img src="upload/banner_01.jpg" alt="" class="img-fluid">
                </div><!-- end banner-img -->
            </div><!-- end banner -->
        </div><!-- end col -->
    </div><!-- end row -->

    <hr class="invis1">

    <div class="custombox prevnextpost clearfix">
        <div class="row">
            <div class="col-lg-6">
                <div class="blog-list-widget">
                    <div class="list-group">
                        <a href="detail.html" class="list-group-item list-group-item-action flex-column align-items-start">
                            <div class="w-100 justify-content-between text-right">
                                <img src="upload/tech_menu_19.jpg" alt="" class="img-fluid float-right">
                                <h5 class="mb-1">5 Beautiful buildings you need to before dying</h5>
                                <small>Prev Post</small>
                            </div>
                        </a>
                    </div>
                </div>
            </div><!-- end col -->

            <div class="col-lg-6">
                <div class="blog-list-widget">
                    <div class="list-group">
                        <a href="detail.html" class="list-group-item list-group-item-action flex-column align-items-start">
                            <div class="w-100 justify-content-between">
                                <img src="upload/tech_menu_20.jpg" alt="" class="img-fluid float-left">
                                <h5 class="mb-1">Let's make an introduction to the glorious world of history</h5>
                                <small>Next Post</small>
                            </div>
                        </a>
                    </div>
                </div>
            </div><!-- end col -->
        </div><!-- end row -->
    </div><!-- end author-box -->

    <hr class="invis1">

    <div class="custombox authorbox clearfix">
        <h4 class="small-title">About author</h4>
        <div class="row">
            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                <img src="upload/author.jpg" alt="" class="img-fluid rounded-circle">
            </div><!-- end col -->

            <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12">
                <h4><a href="#">Jessica</a></h4>
                <p>Quisque sed tristique felis. Lorem <a href="#">visit my website</a> amet, consectetur adipiscing elit. Phasellus quis mi auctor, tincidunt nisl eget, finibus odio. Duis tempus elit quis risus congue feugiat. Thanks for stop Tech Blog!</p>

                <div class="topsocial">
                    <a href="#" data-toggle="tooltip" data-placement="bottom" title="Facebook"><i class="fa fa-facebook"></i></a>
                    <a href="#" data-toggle="tooltip" data-placement="bottom" title="Youtube"><i class="fa fa-youtube"></i></a>
                    <a href="#" data-toggle="tooltip" data-placement="bottom" title="Pinterest"><i class="fa fa-pinterest"></i></a>
                    <a href="#" data-toggle="tooltip" data-placement="bottom" title="Twitter"><i class="fa fa-twitter"></i></a>
                    <a href="#" data-toggle="tooltip" data-placement="bottom" title="Instagram"><i class="fa fa-instagram"></i></a>
                    <a href="#" data-toggle="tooltip" data-placement="bottom" title="Website"><i class="fa fa-link"></i></a>
                </div><!-- end social -->

            </div><!-- end col -->
        </div><!-- end row -->
    </div><!-- end author-box -->

    <hr class="invis1">

    <div class="custombox clearfix">
        <h4 class="small-title">Similar posts</h4>
        <div class="row">
            {% for post in similar_posts %}
            <div class="col-lg-6">
                <div class="blog-box">
                    <div class="post-media">
                        <a href="{{ post.get_absolute_url }}" title="">
                            <img src="{% static 'upload/tech_menu_04.jpg' %}" alt="" class="img-fluid">
                            <div class="hovereffect">
                                <span class=""></span>
                            </div><!-- end hover -->
                        </a>
                    </div><!-- end media -->
                    <div class="blog-meta">
                        <h4><a href="{{ post.get_absolute_url }}" title="">{{ post.title }}</a></h4>
                        <small><a href="blog-category-01.html" title="">Trends</a></small>
                        <small><a href="blog-category-01.html" title="">{{ post.created }}</a></small>
                    </div><!-- end meta -->
                </div><!-- end blog-box -->
            </div><!-- end col -->
            {% empty %}
                <h4>There are no similar posts yet.</h4>
            {% endfor %}
        </div><!-- end row -->
    </div><!-- end custom-box -->

    <hr class="invis1">

    <div class="custombox clearfix">
        {% with comments.count as total_comments %}
        <h4 class="small-title">{{ total_comments }} comment{{ total_comments|pluralize }}</h4>
        {% endwith %}
        <div class="row">
            <div class="col-lg-12">
                <div class="comments-list">
                    {% for comment in comments %}
                        <div class="media">
                            <a class="media-left" href="#">
                                <img src="{% static 'upload/author.jpg' %}" alt="" class="rounded-circle">
                            </a>
                            <div class="media-body">
                                <h4 class="media-heading user_name">{{ comment.name }} <small>{{ comment.created }}</small></h4>
                                <p>{{ comment.body|linebreaks }}</p>
                                <a href="#" class="btn btn-primary btn-sm">Reply</a>
                            </div>
                        </div>
                    {% empty %}
                        <p>There are no comments yet.</p>
                    {% endfor %}
                </div>
            </div><!-- end col -->
        </div><!-- end row -->
    </div><!-- end custom-box -->

    <hr class="invis1">

    <div class="custombox clearfix">
        <h4 class="small-title">Add a comment</h4>
        {% if new_comment %}
            <h2>Your comment has been added.</h2>
        {% else %}
        <div class="row">
            <div class="col-lg-12">
                <form class="form-wrapper" method="post">
                    {% csrf_token %}
                    {% for field in comment_form %}
                            <div>
                                {{ field.label_tag }}
                                {{ field.errors }}
                            </div>
                            <div>
                                {{ field }}
                            </div>
                        {% endfor %}
                    <button type="submit" value="Add comment" class="btn btn-primary">Submit Comment</button>
                </form>
            </div>
        </div>
        {% endif %}
    </div>
{% endblock %}

templates/blog/post/latest_posts.html
{% load static %}
<h2 class="widget-title">Latest Posts</h2>
<div class="trend-videos">
    {% for post in latest_posts %}
    <div class="blog-box">
        <div class="post-media">
            <a href="{{ post.get_absolute_url }}" title="">
                <img src="{% static 'upload/tech_video_01.jpg' %}" alt="" class="img-fluid">
                <div class="hovereffect">
                    <span class="videohover"></span>
                </div><!-- end hover -->
            </a>
        </div><!-- end media -->
        <div class="blog-meta">
            <h4><a href="{{ post.get_absolute_url }}" title="">{{ post.title }}</a></h4>
        </div><!-- end meta -->
    </div><!-- end blog-box -->
    {% endfor %}
</div><!-- end videos -->

templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load static %}
{% load blog_tags %}
{% block title %}My Blog{% endblock %}
{% block content %}
    <div class="blog-list clearfix">
    {% if tag %}
        <h2>Posts tagged "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <div class="blog-box row">
            <div class="col-md-4">
                <div class="post-media">
                    <a href="{{ post.get_absolute_url }}">
                        {% if post.cover %}
                        <img src="{{ post.cover.url }}" alt="" class="img-fluid">
                        <div class="hovereffect"></div>
                        {% endif %}
                    </a>
                </div><!-- end media -->
            </div><!-- end col -->

            <div class="blog-meta big-meta col-md-8">
                <h4><a href="{{ post.get_absolute_url }}" title="">{{ post.title }}</a></h4>
                <p>{{ post.body|markdown|truncatewords_html:25 }}</p>
                <small class="firstsmall"><a class="bg-orange" href="tech-category-01.html" title="">Reviews</a></small>
                <small><a href="detail.html" title="">{{ post.publish }}</a></small>
                <small><a href="tech-author.html" title="">by {{ post.author }}</a></small>
                <small><a href="detail.html" title=""><i class="fa fa-eye"></i> 1114</a></small>
                <div class="tag-cloud-single">
                    <span>Tags</span>
                    {% for tag in post.tags.all %}
                        <small><a href="{% url 'blog_app:post_list_by_tag' tag.slug %}" title="">{{ tag.name }}</a></small>
                        {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </div><!-- end meta -->
            </div>
        </div><!-- end blog-box -->

        <hr class="invis">
    {% endfor %}
    </div><!-- end blog-list -->
    {% include "blog/pagination.html" with page=posts %}
{% endblock %}

templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load static %}
{% load blog_tags %}
{% block title %}Search{% endblock %}
{% block content %}
    <div class="blog-list clearfix">
    {% if query %}
        <h2>Posts containing "{{ query }}"</h2>
        {% with results.count as total_results %}
            <small>Found {{ total_results }} result{{ total_results|pluralize }}</small>
        {% endwith %}

        {% for post in results %}
            <div class="blog-box row">
                <div class="col-md-4">
                    <div class="post-media">
                        <a href="{{ post.get_absolute_url }}">
                            <img src="{% static 'upload/tech_blog_01.jpg' %}" alt="" class="img-fluid">
                            <div class="hovereffect"></div>
                        </a>
                    </div><!-- end media -->
                </div><!-- end col -->

                <div class="blog-meta big-meta col-md-8">
                    <h4><a href="{{ post.get_absolute_url }}" title="">{{ post.title }}</a></h4>
                    <p>{{ post.body|markdown|truncatewords_html:5 }}</p>
                    <small class="firstsmall"><a class="bg-orange" href="tech-category-01.html" title="">Reviews</a></small>
                    <small><a href="detail.html" title="">{{ post.publish }}</a></small>
                    <small><a href="tech-author.html" title="">by {{ post.author }}</a></small>
                    <small><a href="detail.html" title=""><i class="fa fa-eye"></i> 1114</a></small>
                    <div class="tag-cloud-single">
                        <span>Tags</span>
                        {% for tag in post.tags.all %}
                            <small><a href="{% url 'blog_app:post_list_by_tag' tag.slug %}" title="">{{ tag.name }}</a></small>
                            {% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </div><!-- end meta -->
                </div>
            </div><!-- end blog-box -->

            <hr class="invis">
        {% empty %}
            <h4> There are no results for your query.</h4>
        {% endfor %}
        <p><a href="{% url "blog_app:post_search" %}">Search again</a></p>
        {% else %}
        <div class="custombox clearfix">
            <h4 class="small-title">Seach for </h4>
            <div class="row">
                <div class="col-lg-12">
                    <form class="form-wrapper" method="get">

                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" value="Search" class="btn btn-primary">Search</button>

                    </form>
                </div>
            </div>
        </div>

    {% endif %}
    </div><!-- end blog-list -->
{% endblock %}

templates/blog/post/share.html
{% extends 'blog/base.html' %}
{% block title %}Share a post{% endblock %}
{% block content %}
    {% if sent %}
        <h4 class="small-title">E-mail successfully sent!</h4>
        <hr class="invis1">
        <p>"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.</p>
    {% else %}
        <div class="custombox clearfix">
            <h4 class="small-title">Share "{{ post.title }}" by e-mail</h4>
            <div class="row">
                <div class="col-lg-12">
                    <form class="form-wrapper" method="post">

                        {% csrf_token %}
                        {% for field in form %}
                            <div>
                                {{ field.label_tag }}
                                {{ field.errors }}
                            </div>
                            <div>
                                {{ field }}
                            </div>
                        {% endfor %}
                        <button type="submit" value="Send e-mail" class="btn btn-primary">Send Email</button>

                    </form>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}